version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/userdb
    depends_on:
      - mongodb

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/orderdb
    depends_on:
      - mongodb

volumes:
  mongo-data: